### ISSUE TITLE
HA version

### ISSUE THREAD

**Issue by Repsionu** [bdraco/profiler#1]
Tried this after reverting to 0.115,6 from 0.116b1- no go :-( Installed OK (and via HACS afterwards)- but no integration nor service...
Feeling **dumb** now...
Must I be on latest 0.116 beta for this or?
HACS installed OK, add integration (search prof...) no go- must I look into the mirror- or restart for 5X?

**Comment by bdraco** [comment]
This will be released with 0.117 tomorrow.
